### ISSUE TITLE
Documentation suggestions

### ISSUE THREAD

**Issue by dza6549** [NumesSanguis/FACSvatar#1]
Hi NumesSanguis

This project looks great!

May I suggest the following documentation changes in the How to Run guide?
1: Due to the use of function async Python version 3.5 or greater is required
2: you include six and pandas libraries as python dependencies 
3: user to load Unity Scene MB_demo_asian_female_ready
4: Terminal: python pub_facs.py (/modules/01_facs-from-csv/) be moved to Step 4 (it runs before Terminal: python pub_blend.py (/modules/02_facs-to-blendshapes/) is loaded)

Cheers!

**Comment by NumesSanguis** [comment]
Thank you for your suggestions!

As you've probably noticed, the documentation is really bad at the moment. I'm still changing the structure of the software quite some bit, so if I write the documentation now, I've to keep changing it.
Expect to have a huge improvement to the documentation by the end of this month, but hopefully earlier.

**Comment by dza6549** [comment]
Hi NumesSanguis

Thanks for your reply.

Cheers
