### ISSUE TITLE
Some confusion about n_array

### ISSUE THREAD

**Issue by xjqxzh1** [NumesSanguis/FACSvatar#11]
Hi NumesSanguis
I‘m learning the bridge module about how to smooth data.I notice that in softmax_smooth2 function the first number of n_array is set to 1.But in facsvatar paper, the smoothing formula shows n start at 0.I wonder about the difference between the two ways.Hope you could give me some suggestions.
Thanks again.

**Comment by NumesSanguis** [comment]
Thank you for pointing this out. I didn't notice this discrepancy between paper and code. In practice the result of the code and paper is the same. This would be the formula currently used in the code:
![FACSvatar_smooth_CodeCogsEqn](https://user-images.githubusercontent.com/8008618/55403711-67b45080-5591-11e9-947b-512e19deeb34.png)

Let's take an example where we have an array of `len(Xn)` = 2, with `X0 = .4` and `X1 = .25`. We also set `\alpha = 0.3`.
On a calculator, this gives the exact same outcome:
`(e^(-.3*0)*.4 + e^(-.3*1)*.25) / ((e^(-.3*0) + e^(-.3*1))  =  0.336166`
`(e^(-.3*1)*.4 + e^(-.3*2)*.25) / ((e^(-.3*1) + e^(-.3*2))  =  0.336166`

I hope this clears the confusion?

**Comment by xjqxzh1** [comment]
> Thank you for pointing this out. I didn't notice this discrepancy between paper and code. In practice the result of the code and paper is the same. This would be the formula currently used in the code:
> ![FACSvatar_smooth_CodeCogsEqn](https://user-images.githubusercontent.com/8008618/55403711-67b45080-5591-11e9-947b-512e19deeb34.png)
> 
> Let's take an example where we have an array of `len(Xn)` = 2, with `X0 = .4` and `X1 = .25`. We also set `\alpha = 0.3`.
> On a calculator, this gives the exact same outcome:
> Paper: `(e^(-.3*0)*.4 + e^(-.3*1)*.25) / ((e^(-.3*0) + e^(-.3*1)) = 0.336166`
> Code: `(e^(-.3*1)*.4 + e^(-.3*2)*.25) / ((e^(-.3*1) + e^(-.3*2)) = 0.336166`
> 
> I hope this clears the confusion?

Now I have a more intuitive understanding of this formula.Thanks a lot!!!
