### ISSUE TITLE
Error running MB_demo_asian_femaile_ready scene

### ISSUE THREAD

**Issue by dza6549** [NumesSanguis/FACSvatar#2]
Hi NumesSanguis

I get the following 715 errors when using How to Run directions

JsonReaderException: Unexpected character encountered while parsing value: h. Path '', line 0, position 0.
Newtonsoft.Json.JsonTextReader.ParseValue () (at <97722d3abc9f4cf69f9e21e6770081b3>:0)
Newtonsoft.Json.JsonTextReader.Read () (at <97722d3abc9f4cf69f9e21e6770081b3>:0)
Newtonsoft.Json.Linq.JObject.Load (Newtonsoft.Json.JsonReader reader, Newtonsoft.Json.Linq.JsonLoadSettings settings) (at <97722d3abc9f4cf69f9e21e6770081b3>:0)
Newtonsoft.Json.Linq.JObject.Parse (System.String json, Newtonsoft.Json.Linq.JsonLoadSettings settings) (at <97722d3abc9f4cf69f9e21e6770081b3>:0)
Newtonsoft.Json.Linq.JObject.Parse (System.String json) (at <97722d3abc9f4cf69f9e21e6770081b3>:0)
ZeroMQFACSvatar.HandleMessage (System.String subMsg) (at Assets/Scripts/ZeroMQFACSvatar.cs:85)
NetMqListener.Update () (at Assets/Scripts/ZeroMQFACSvatar.cs:45)
ZeroMQFACSvatar.Update () (at Assets/Scripts/ZeroMQFACSvatar.cs:104)

Windows 10 Home
Unity 2017.3.1f1
Current libzmq version is 4.1.6
Current  pyzmq version is 17.0.0
Python 3.6.5

Her head moves but she looks very unwell :)

Please let me know if I can provide any further information.

Cheers

**Comment by NumesSanguis** [comment]
Thank you for your extensive error report.

I've now been testing on Ubuntu 16.04, and even though I think I get that error once, it didn't affect the running of the software. I'm supporting both Ubuntu & Windows, so I'll make sure it runs on both platforms.

The error seems to be with the JSON decoder library that the Unity project is using. If that is indeed the reason, I'll try a JSON-to-class unpack solution.

I assume you're using the master branch of FACSvatar? In that branch the raw data of OpenFace is still used. It might also be that there the the wrong rotation is still mapped to the wrong bone. In a branch, I added a smoothing function, so it should look much nicer.

Please wait a few days, and the master branch will be improved.

**Comment by dza6549** [comment]
Hi NumesSanguis

Yes I was using the master branch. I'll have a poke around the branches and keep my eye on master.

Thanks

**Comment by NumesSanguis** [comment]
I've given an update to the master branch. I'm now going to test the system on Windows.

**Comment by dza6549** [comment]
I'll give it a go and let you know thanks.
