### ISSUE TITLE
Will there be a windows stand-alone for Blender?

### ISSUE THREAD

**Issue by delebash** [NumesSanguis/FACSvatar#20]
I see the standalone for Unity.  Do you use this version in blender as well.  I would like to run the windows version to the blender add-on without having to install docker.

Thanks

**Comment by NumesSanguis** [comment]
You should see FACSvatar as a Framework that transfers data from 1 program (e.g. OpenFace), manipulates it, and forwards it to a visualization program (e.g. Unity3D / Blender). All this is done by passing information between modules.
The Unity3D is also not stand-alone (It requires OpenFace data and FACSvatar modules running).

So far, all FACSvatar modules are in Python. You have 2 options. Install Docker and run all the modules in containers. Or set-up a Python environment and run all modules in separate terminals.
For the Python (no Docker) approach, you can find the install instructions here: https://facsvatar.readthedocs.io/en/latest/defaultsetup.html#facsvatar-modules

Then you can find the instructions on how to run everything here: https://facsvatar.readthedocs.io/en/latest/firstrun.html
I haven't updated the documentation for the new Blender add-on yet. I'm sorry.

**Comment by delebash** [comment]
Thanks!
